spring.application.name=babyq
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/babyq_db
spring.datasource.username=root
spring.datasource.password=manuga@2005$%

# Hibernate (JPA) Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
