# Set Application Name
spring.application.name=babyQ_backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/babyQ_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Dinu1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8082

spring.web.resources.static-locations=file:uploads/
# spring.security.enabled=false

jwt.secret=7db80d404acddc4f9ffd22c5d832095160e48bd9fb270f4f08c2cae11ceaff67
jwt.expiration=3600000 # 1 hour in milliseconds

