/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AllergiesHistory`; params?: Router.UnknownInputParams; } | { pathname: `/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/Channel`; params?: Router.UnknownInputParams; } | { pathname: `/ChannelHistory`; params?: Router.UnknownInputParams; } | { pathname: `/Chatbot`; params?: Router.UnknownInputParams; } | { pathname: `/CHDR`; params?: Router.UnknownInputParams; } | { pathname: `/Feeding`; params?: Router.UnknownInputParams; } | { pathname: `/GrowthDataPage`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landingPage1`; params?: Router.UnknownInputParams; } | { pathname: `/landingPage2`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/mental-health`; params?: Router.UnknownInputParams; } | { pathname: `/milestones`; params?: Router.UnknownInputParams; } | { pathname: `/newborn-care`; params?: Router.UnknownInputParams; } | { pathname: `/parent1`; params?: Router.UnknownInputParams; } | { pathname: `/parent2`; params?: Router.UnknownInputParams; } | { pathname: `/registerSelect`; params?: Router.UnknownInputParams; } | { pathname: `/VaccinationHistory`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/AllergiesHistory`; params?: Router.UnknownOutputParams; } | { pathname: `/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/Channel`; params?: Router.UnknownOutputParams; } | { pathname: `/ChannelHistory`; params?: Router.UnknownOutputParams; } | { pathname: `/Chatbot`; params?: Router.UnknownOutputParams; } | { pathname: `/CHDR`; params?: Router.UnknownOutputParams; } | { pathname: `/Feeding`; params?: Router.UnknownOutputParams; } | { pathname: `/GrowthDataPage`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/landingPage1`; params?: Router.UnknownOutputParams; } | { pathname: `/landingPage2`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/mental-health`; params?: Router.UnknownOutputParams; } | { pathname: `/milestones`; params?: Router.UnknownOutputParams; } | { pathname: `/newborn-care`; params?: Router.UnknownOutputParams; } | { pathname: `/parent1`; params?: Router.UnknownOutputParams; } | { pathname: `/parent2`; params?: Router.UnknownOutputParams; } | { pathname: `/registerSelect`; params?: Router.UnknownOutputParams; } | { pathname: `/VaccinationHistory`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/AllergiesHistory${`?${string}` | `#${string}` | ''}` | `/AppNavigator${`?${string}` | `#${string}` | ''}` | `/Channel${`?${string}` | `#${string}` | ''}` | `/ChannelHistory${`?${string}` | `#${string}` | ''}` | `/Chatbot${`?${string}` | `#${string}` | ''}` | `/CHDR${`?${string}` | `#${string}` | ''}` | `/Feeding${`?${string}` | `#${string}` | ''}` | `/GrowthDataPage${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/landingPage1${`?${string}` | `#${string}` | ''}` | `/landingPage2${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/mental-health${`?${string}` | `#${string}` | ''}` | `/milestones${`?${string}` | `#${string}` | ''}` | `/newborn-care${`?${string}` | `#${string}` | ''}` | `/parent1${`?${string}` | `#${string}` | ''}` | `/parent2${`?${string}` | `#${string}` | ''}` | `/registerSelect${`?${string}` | `#${string}` | ''}` | `/VaccinationHistory${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AllergiesHistory`; params?: Router.UnknownInputParams; } | { pathname: `/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/Channel`; params?: Router.UnknownInputParams; } | { pathname: `/ChannelHistory`; params?: Router.UnknownInputParams; } | { pathname: `/Chatbot`; params?: Router.UnknownInputParams; } | { pathname: `/CHDR`; params?: Router.UnknownInputParams; } | { pathname: `/Feeding`; params?: Router.UnknownInputParams; } | { pathname: `/GrowthDataPage`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landingPage1`; params?: Router.UnknownInputParams; } | { pathname: `/landingPage2`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/mental-health`; params?: Router.UnknownInputParams; } | { pathname: `/milestones`; params?: Router.UnknownInputParams; } | { pathname: `/newborn-care`; params?: Router.UnknownInputParams; } | { pathname: `/parent1`; params?: Router.UnknownInputParams; } | { pathname: `/parent2`; params?: Router.UnknownInputParams; } | { pathname: `/registerSelect`; params?: Router.UnknownInputParams; } | { pathname: `/VaccinationHistory`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
