# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/babyq_db
spring.datasource.username=root
spring.datasource.password=Avindhya2003

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8082

# Disable security for testing purposes
spring.security.enabled=false















