/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ResetPW`; params?: Router.UnknownInputParams; } | { pathname: `/ResetPW2`; params?: Router.UnknownInputParams; } | { pathname: `/doctorSearchResults`; params?: Router.UnknownInputParams; } | { pathname: `/healthcareProvider1`; params?: Router.UnknownInputParams; } | { pathname: `/healthcareProvider2`; params?: Router.UnknownInputParams; } | { pathname: `/healthcareProvider3`; params?: Router.UnknownInputParams; } | { pathname: `/healthcareProvider4`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landingPage1`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/parent1`; params?: Router.UnknownInputParams; } | { pathname: `/landingPage2`; params?: Router.UnknownInputParams; } | { pathname: `/registerSelect`; params?: Router.UnknownInputParams; } | { pathname: `/resetDone`; params?: Router.UnknownInputParams; } | { pathname: `/resetPassword`; params?: Router.UnknownInputParams; } | { pathname: `/parent2`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/ResetPW`; params?: Router.UnknownOutputParams; } | { pathname: `/ResetPW2`; params?: Router.UnknownOutputParams; } | { pathname: `/doctorSearchResults`; params?: Router.UnknownOutputParams; } | { pathname: `/healthcareProvider1`; params?: Router.UnknownOutputParams; } | { pathname: `/healthcareProvider2`; params?: Router.UnknownOutputParams; } | { pathname: `/healthcareProvider3`; params?: Router.UnknownOutputParams; } | { pathname: `/healthcareProvider4`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/landingPage1`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/parent1`; params?: Router.UnknownOutputParams; } | { pathname: `/landingPage2`; params?: Router.UnknownOutputParams; } | { pathname: `/registerSelect`; params?: Router.UnknownOutputParams; } | { pathname: `/resetDone`; params?: Router.UnknownOutputParams; } | { pathname: `/resetPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/parent2`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/ResetPW${`?${string}` | `#${string}` | ''}` | `/ResetPW2${`?${string}` | `#${string}` | ''}` | `/doctorSearchResults${`?${string}` | `#${string}` | ''}` | `/healthcareProvider1${`?${string}` | `#${string}` | ''}` | `/healthcareProvider2${`?${string}` | `#${string}` | ''}` | `/healthcareProvider3${`?${string}` | `#${string}` | ''}` | `/healthcareProvider4${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/landingPage1${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/parent1${`?${string}` | `#${string}` | ''}` | `/landingPage2${`?${string}` | `#${string}` | ''}` | `/registerSelect${`?${string}` | `#${string}` | ''}` | `/resetDone${`?${string}` | `#${string}` | ''}` | `/resetPassword${`?${string}` | `#${string}` | ''}` | `/parent2${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ResetPW`; params?: Router.UnknownInputParams; } | { pathname: `/ResetPW2`; params?: Router.UnknownInputParams; } | { pathname: `/doctorSearchResults`; params?: Router.UnknownInputParams; } | { pathname: `/healthcareProvider1`; params?: Router.UnknownInputParams; } | { pathname: `/healthcareProvider2`; params?: Router.UnknownInputParams; } | { pathname: `/healthcareProvider3`; params?: Router.UnknownInputParams; } | { pathname: `/healthcareProvider4`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landingPage1`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/parent1`; params?: Router.UnknownInputParams; } | { pathname: `/landingPage2`; params?: Router.UnknownInputParams; } | { pathname: `/registerSelect`; params?: Router.UnknownInputParams; } | { pathname: `/resetDone`; params?: Router.UnknownInputParams; } | { pathname: `/resetPassword`; params?: Router.UnknownInputParams; } | { pathname: `/parent2`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
